services:
  - type: web
    name: compatify
    runtime: node
    buildCommand: npm install && npm run seed
    startCommand: npm run deploy
    envVars:
      - key: NODE_ENV
        value: production
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
